# Generated by Django 5.1.1 on 2024-09-19 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="notes",
            new_name="note",
        ),
        migrations.RenameField(
            model_name="restaurant",
            old_name="notes",
            new_name="note",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="link_google_maps",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="review",
            name="favourite",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="osm_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="osm_type",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="gourmand",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
