# Generated by Django 5.1 on 2024-08-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurant_coords_restaurant_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='coords',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
