# Generated by Django 5.1.1 on 2024-09-20 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_notes_log_note_rename_notes_restaurant_note_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AddField(
            model_name="listitem",
            name="order",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gourmand",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gourmand",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Log",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
