# Generated by Django 5.1.1 on 2024-09-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_review_restaurant_remove_review_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="list",
            old_name="user",
            new_name="author",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="osm_id",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="osm_type",
        ),
        migrations.AddField(
            model_name="gourmand",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gourmand",
            name="country",
            field=models.CharField(default="placeholder", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="google_maps_place_id",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="list",
            unique_together={("name", "slug")},
        ),
    ]
