# Generated by Django 5.1 on 2024-08-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_restaurant_coords_alter_restaurant_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
    ]
