# Generated by Django 5.1.1 on 2024-09-26 04:29

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_user_list_author_remove_restaurant_osm_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gourmand",
            name="city",
        ),
        migrations.AlterField(
            model_name="gourmand",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
