# Generated by Django 5.1.1 on 2024-09-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_gourmand_city_alter_gourmand_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(default="placeholder", max_length=200),
            preserve_default=False,
        ),
    ]
